site_name: Association "Cloud Native Suisse Romande"
site_description: >-
  Our association aims to connect end users, contributors, and maintainers of cloud native computing projects,
  within the Suisse Romande region.
copyright: >-
  Copyright &copy; 2024-2025 - Association "Cloud Native Suisse Romande" and all contributors.
  The content and the license are licensed under CC BY 4.0
repo_url: https://github.com/cloud-native-suisse-romande/website
repo_name: GitHub Repo
edit_uri: edit/main/
site_url: https://cloud-native-romandy.ch/

# Build
site_dir: _site
docs_dir: .

nav:
  - Events:
    - Overview: events/README.md
    - KCD Suisse Romande 2025: events/kcd/README.md
    - Cloud Native Meetups: events/meetups/README.md
    - Kubetrain Europe: events/kubetrain/README.md
  - "Join Us!":
    - Join the Association: members/join.md
  - Governance:
    - Association Charter: governance/association/charter.md
    - Code of Conduct: governance/bylaws/CODE_OF_CONDUCT.md
    - Membership Process: governance/policies/2_membership-process.md 
    - Current Members: governance/association/members.md
  - Resources:
    - Privacy Policy: governance/policies/1_privacy-policy.md
    - Contributing to this Site: CONTRIBUTING.md
    - Content License: LICENSE.txt
    - Contacts: contacts.md

plugins:
  - search
  - autorefs
  - macros
  - mkdocs-pdf
  - social
  - same-dir
  - group:
      enabled: !ENV [FULL_BUILD, true]
      plugins:
      - multirepo:
          # TODO: Change to True once works
          cleanup: false
          keep_docs_dir: true
          nav_repos:
          - name: governance
            import_url: 'https://github.com/cloud-native-suisse-romande/governance?branch=main&edit_uri=/blob/main/'
  - redirects:
      redirect_maps:
        'events/kcd/README.md': https://kcd.cloud-native-romandy.ch/


# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists

# Theme
theme:
  name: material
  custom_dir: overrides
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/images/logo/logo.svg
  logo: assets/images/logo/logo.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/css/theme.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloud-native-suisse-romande
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cloud-native-suisse-romande
      name: LinkedIn
