name: Continuous Integration

on:
  # We have deploy there
  # push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
        
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: "true"
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build in the dev container image
        uses: devcontainers/ci@v0.3
        with:
            imageName: ghcr.io/cloud-native-suisse-romande/website-builder
            cacheFrom: ghcr.io/cloud-native-suisse-romande/website-builder
            push: never
            runCmd: |
              mkdocs build
            env: |
              FULL_BUILD=true
              INSIDERS=true
